version: "3"
services:
  proxy:
    build:
      context: ./proxy
    ports:
      - 8081:80
  redis-server:
    image: "redis"
    ports:
      - "6739:6739"
  node-app:
    restart: on-failure
    build:
      context: ./back
    ports:
      - "8080:8080"
    container_name: api-server
  ui:
    build:
      context: ./front
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./front:/usr/app
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
volumes:
  postgres:
